Camera adding
UralmashFox/not_Skin_bastard pull request #1
Opened 2019-11-10 18:47 UTC by UralmashFox

I don't know, what will be if I push "create pull request, but I try"...

2019-11-11 23:48 UTC, l1va requested changes

2019-11-11 23:48 UTC, l1va commented on README.md
>  This magic python code makes my creation walk :3 Just impressive, my baby does it's first steps ^_^
Happy birthday! Wish you fewer bugs and green CI

2019-11-11 23:48 UTC, l1va commented on spot/src/myrobot/urdf/thespot.urdf.xacro
> +<<<< camera_adding
missed conflict line

2019-11-11 23:48 UTC, l1va commented on spot/src/thespot_python/scripts/main.py
> +    rospy.loginfo("I heard %s",data.data)
i think this code is not needed here now

2019-11-11 23:48 UTC, l1va commented on spot/src/thespot_python/scripts/subscriber.py
> +        cv2.imwrite("/home/marina/spot/pic"+t+".png", cv2_img)
hardcode, it will not work on my laptop :(

2019-11-13 07:04 UTC, UralmashFox commented
Now camera is added to the model.

2019-11-13 07:04 UTC, merged